on:
  workflow_dispatch:
    inputs:
      plugins:
        description: Repo urls of plugin need to be bundled
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: Set up Golang environment
        uses: actions/setup-go@v2
        with:
          go-version: "^1.13.1"
      - name: Login docker registry  (ghcr.io)
        run: |-
          # new login with new container registry url and PAT
          # login to Github ghcr.io
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      # - name: Set up xcaddy
      #   run: |-
      #     go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      # - name: Build caddy with plugins
      #   run: |-
      #     xcaddy build $(cat plugins  | xargs -I {} echo -n " --with {}")
      - name: Build Docker image and push
        run: |-
          docker buildx build \
              --platform linux/amd64,linux/arm64 \
              --build-arg CADDY_PLUGIN="$(cat plugins  | xargs -I {} echo -n " --with {}")"
              --tag ghcr.io/${GITHUB_REPOSITORY}:$(date +"%Y%m%d%H%M%S") \
              --tag ghcr.io/${GITHUB_REPOSITORY}:latest \
              --push .
      - name: Generate release note
        run: |-
          echo "# Archtype" >> release-note.md
          echo "Linux amd64" >> release-note.md
          # echo "# Caddy version" >> release-note.md
          # ./caddy version >> release-note.md
          echo "# Bundled Plugins" >> release-note.md
          cat plugins >> release-note.md
          echo "RELEASE_NAME=v$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV
      - name: upload executable to artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: |
            # caddy
            release-note.md
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "caddy"
          bodyFile: "release-note.md"
          name: ${{ env.RELEASE_NAME }}
          tag: ${{ env.RELEASE_NAME }}
          token: ${{ secrets.GITHUB_TOKEN }}
